### ISSUE TITLE
Implement generated "unique" Item Names with [Syllabore]

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [Synthesis-Collective/SynthesisRPGLoot#33]
https://github.com/kesac/Syllabore

unsure if I make them used in a prefix or as a full on name replacement
- `([Name]'s (optional)) [Rarity_Label] [Item_Name] [Enchantemnts(Optional)]` aka the name of a "legendary owner/deity" as prefix
- `[Rarity_Label] [Item_Name] [Enchantemnts(Optional)] (of [Name](optional)) ` aka the name of a "legendary owner/deity" as suffix
- `[Rarity Label] [Name as Item Name(obviously optional)] [Enchantments(Optional)]` aka Mjolnir instead of War-hammer. 

(All `optionals` should/will be configurable per rarity)

**Comment by EzioTheDeadPoet** [comment]
Just a note for anyone looking at this.
While the recent updates where all very close together this one likely will take a bit longer since I also have other deadlines waiting for me.

But I don't expect this to turn stale for nearly 2 years like the last overhaul did.

**Comment by MartinHaeusler** [comment]
@EzioTheDeadPoet this does seem **very** cool, I would use this :)

**Comment by EzioTheDeadPoet** [comment]
> @EzioTheDeadPoet this does seem **very** cool, I would use this :)

It is actually coded already but I don't want to push it as a new release before I figure out a way to make the documentation for it.

I could just redirect to the Syllabore documentation for a number of things but since that would only apply for the theoretical description of the features it would be confusing. And well on top of that the "current" settings are already very confusing and a big wall of text.

And so rn I am really struggling on how to best document all those features.

I hope that I'll get it done sometime this year but I am really struggling to find the motivation. 😅


That said you should be able to download the 4.0 branch with Syllabore support and add it as a local "existing" patcher in synthesis, and try it out. (You sadly can't use the versioning system because Synthesis doesn't like it when the project is named differently than in the main branch, and I also took the chance of that 4.0 to actually rename the project files as well to Synthesis RPG loot.)
