### ISSUE TITLE
Patcher doesn't work on mod-added weapons and armor

### ISSUE THREAD

**Issue by saberthesword** [Synthesis-Collective/SynthesisRPGLoot#37]
Tried adding a few non-base game+dlc weapon and armor mods and none of them got patched.

Also is it possible to request a feature where we can select which mods to patch? since the base game weapons already have their own mod-added enchanted variants.

**Comment by EzioTheDeadPoet** [comment]
this patcher works based on leveled lists. 
if the mod you use doesn't add it's weapons to leveled lists, then they won't get enchanted.
Also this mod is not an tool to distribute vanilla enchantments for modded weapons.
This mod is to overhaul the loot system to introduce new enchantment rarity types similar to ARPGs or games like Borderlands.
