### ISSUE TITLE
Implement-"Runtime"-Build-Cache

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [Synthesis-Collective/SynthesisRPGLoot#42]
Investigating if building a runtime-"cache" can improve perfromance for bigger lists.

Theory is that the frequent use of `State.LinkCache.TryResolve<>` especially inside of loops causes exponentially longer runtimes.
So creating a custom "cache" that it purpose build for each loop stage should  improve performance.

**Comment by EzioTheDeadPoet** [comment]
This could later be expanded into making a permanent build cache that saves generated leveled lists based on their editor IDs.

This would require some way of invalidating the cache and would bring the risk of the RNG elements not being fully deterministic anymore. On the other hand IF items and lists are loaded from the cache then it would only apply for new armor and weapon mods that aren't cached yet. So the worst case would be that items that should get unique names get some already existing names generated. And similar enchantments.

**Comment by Noggog** [comment]
> Theory is that the frequent use of State.LinkCache.TryResolve<> especially inside of loops causes exponentially longer runtimes.
So creating a custom "cache" that it purpose build for each loop stage should improve performance.

It does, related to this card:  https://github.com/Mutagen-Modding/Mutagen/issues/229

Once that's done, it should go back to being mostly instant lookups again, without degradation the more records are added to the patch

**Comment by EzioTheDeadPoet** [comment]
Before:
![image](https://github.com/user-attachments/assets/5c47cc45-bcd2-493f-975d-6ff8f1cddc76)
After:
![image](https://github.com/user-attachments/assets/80ae371e-c753-481a-bb22-65b09c4c8c7b)
